src/CPO/AdminBundle/Entity/Kosnica.php
<?php

namespace CPO\AdminBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Kosnica
 *
 * @ORM\Table(name="kosnica")
 * @ORM\Entity(repositoryClass="CPO\AdminBundle\Repository\KosnicaRepository")
 */
class Kosnica
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="naslov", type="string", length=255)
     */
    private $naslov;

    /**
     * @var integer
     *
     * @ORM\Column(name="identifikacijski_broj", type="integer", length=255, unique=true)
     */
    private $identifikacijski_broj;


    /**
     * @var integer
     *
     * @ORM\Column(name="izdvoji", type="integer", length=255)
     */
    private $izdvoji;

    /**
     * @var string
     *
     * @ORM\Column(name="temperatura", type="string", length=255)
     */
    private $temperatura;

    /**
     * @var string
     *
     * @ORM\Column(name="vlaga", type="string", length=255)
     */
    private $vlaga;

    /**
     * @var string
     *
     * @ORM\Column(name="promjena", type="string", length=255)
     */
    private $promjena;

    /**
     * @var string
     *
     * @ORM\Column(name="broj_pcela", type="string", length=255)
     */
    private $broj_pcela;

    /**
     * @var string
     *
     * @ORM\Column(name="tezina", type="string", length=255)
     */
    private $tezina;

    /**
     * @var string
     *
     * @ORM\Column(name="temperatura_unutra", type="string", length=255)
     */
    private $temperaturaUnutra;

    /**
     * @var string
     *
     * @ORM\Column(name="vlaga_unutra", type="string", length=255)
     */
    private $vlagaUnutra;

    /**
     * @var string
     *
     * @ORM\Column(name="baterija", type="string", length=255)
     */
    private $baterija;

    /**
     * @var string
     *
     * @ORM\Column(name="vrijeme", type="string", length=255, nullable=true)
     */
    private $vrijeme;

    /**
     * @var string
     *
     * @ORM\Column(name="lokacija", type="string", length=255, nullable=true)
     */
    private $lokacija;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datum", type="datetime")
     */
    private $datum;

    /**
     * @var int
     *
     * @ORM\Column(name="sleep_mode", type="integer")
     */
    private $sleepMode;

    /**
     * @var int
     *
     * @ORM\Column(name="sustav_zastite_zivotinja", type="integer")
     */
    private $sustavZastiteZivotinja;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set naslov
     *
     * @param string $naslov
     *
     * @return Kosnica
     */
    public function setNaslov($naslov)
    {
        $this->naslov = $naslov;

        return $this;
    }

    /**
     * Get naslov
     *
     * @return string
     */
    public function getNaslov()
    {
        return $this->naslov;
    }

    /**
     * Set identifikacijski_broj
     *
     * @param integer $identifikacijski_broj
     *
     * @return Kosnica
     */
    public function setIdentifikacijskiBroj($identifikacijski_broj)
    {
        $this->identifikacijski_broj = $identifikacijski_broj;

        return $this;
    }

    /**
     * Get identifikacijski_broj
     *
     * @return integer
     */
    public function getIdentifikacijskiBroj()
    {
        return $this->identifikacijski_broj;
    }

    /**
     * Set izdvoji
     *
     * @param integer $izdvoji
     *
     * @return Kosnica
     */
    public function setIzdvoji($izdvoji)
    {
        $this->izdvoji = $izdvoji;

        return $this;
    }

    /**
     * Get izdvoji
     *
     * @return integer
     */
    public function getIzdvoji()
    {
        return $this->izdvoji;
    }

    /**
     * Set temperatura
     *
     * @param string $temperatura
     *
     * @return Kosnica
     */
    public function setTemperatura($temperatura)
    {
        $this->temperatura = $temperatura;

        return $this;
    }

    /**
     * Get temperatura
     *
     * @return string
     */
    public function getTemperatura()
    {
        return $this->temperatura;
    }

    /**
     * Set vlaga
     *
     * @param string $vlaga
     *
     * @return Kosnica
     */
    public function setVlaga($vlaga)
    {
        $this->vlaga = $vlaga;

        return $this;
    }

    /**
     * Get vlaga
     *
     * @return string
     */
    public function getVlaga()
    {
        return $this->vlaga;
    }

    /**
     * Set promjena
     *
     * @param string $promjena
     *
     * @return Kosnica
     */
    public function setPromjena($promjena)
    {
        $this->promjena = $promjena;

        return $this;
    }

    /**
     * Get promjena
     *
     * @return string
     */
    public function getPromjena()
    {
        return $this->promjena;
    }

    /**
     * Set tezina
     *
     * @param string $tezina
     *
     * @return Kosnica
     */
    public function setTezina($tezina)
    {
        $this->tezina = $tezina;

        return $this;
    }

    /**
     * Get tezina
     *
     * @return string
     */
    public function getTezina()
    {
        return $this->tezina;
    }

    /**
     * Set temperaturaUnutra
     *
     * @param string $temperaturaUnutra
     *
     * @return Kosnica
     */
    public function setTemperaturaUnutra($temperaturaUnutra)
    {
        $this->temperaturaUnutra = $temperaturaUnutra;

        return $this;
    }

    /**
     * Get temperaturaUnutra
     *
     * @return string
     */
    public function getTemperaturaUnutra()
    {
        return $this->temperaturaUnutra;
    }

    /**
     * Set vlagaUnutra
     *
     * @param string $vlagaUnutra
     *
     * @return Kosnica
     */
    public function setVlagaUnutra($vlagaUnutra)
    {
        $this->vlagaUnutra = $vlagaUnutra;

        return $this;
    }

    /**
     * Get vlagaUnutra
     *
     * @return string
     */
    public function getVlagaUnutra()
    {
        return $this->vlagaUnutra;
    }

    /**
     * Set baterija
     *
     * @param string $baterija
     *
     * @return Kosnica
     */
    public function setBaterija($baterija)
    {
        $this->baterija = $baterija;

        return $this;
    }

    /**
     * Get baterija
     *
     * @return string
     */
    public function getBaterija()
    {
        return $this->baterija;
    }

    /**
     * Set vrijeme
     *
     * @param string $vrijeme
     *
     * @return Kosnica
     */
    public function setVrijeme($vrijeme)
    {
        $this->vrijeme = $vrijeme;

        return $this;
    }

    /**
     * Get vrijeme
     *
     * @return string
     */
    public function getVrijeme()
    {
        return $this->vrijeme;
    }

    /**
     * Set lokacija
     *
     * @param string $lokacija
     *
     * @return Kosnica
     */
    public function setLokacija($lokacija)
    {
        $this->lokacija = $lokacija;

        return $this;
    }

    /**
     * Get lokacija
     *
     * @return string
     */
    public function getLokacija()
    {
        return $this->lokacija;
    }

    /**
     * Set $broj_pcela
     *
     * @param string $broj_pcela
     *
     * @return Kosnica
     */
    public function setBrojPcela($broj_pcela)
    {
        $this->broj_pcela = $broj_pcela;

        return $this;
    }

    /**
     * Get $broj_pcela
     *
     * @return string
     */
    public function getBrojPcela()
    {
        return $this->broj_pcela;
    }

    /**
     * Set datum
     *
     * @param \DateTime $datum
     *
     * @return Kosnica
     */
    public function setDatum($datum)
    {
        $this->datum = $datum;

        return $this;
    }

    /**
     * Get datum
     *
     * @return \DateTime
     */
    public function getDatum()
    {
        return $this->datum;
    }

    /**
     * Set sleepMode
     *
     * @param integer $sleepMode
     *
     * @return Kosnica
     */
    public function setSleepMode($sleepMode)
    {
        $this->sleepMode = $sleepMode;

        return $this;
    }

    /**
     * Get sleepMode
     *
     * @return int
     */
    public function getSleepMode()
    {
        return $this->sleepMode;
    }

    /**
     * Set sustavZastiteZivotinja
     *
     * @param integer $sustavZastiteZivotinja
     *
     * @return Kosnica
     */
    public function setSustavZastiteZivotinja($sustavZastiteZivotinja)
    {
        $this->sustavZastiteZivotinja = $sustavZastiteZivotinja;

        return $this;
    }

    /**
     * Get sustavZastiteZivotinja
     *
     * @return int
     */
    public function getSustavZastiteZivotinja()
    {
        return $this->sustavZastiteZivotinja;
    }
}

src/CPO/AdminBundle/Resources/views/Admin/about.html.twig
{% extends "@CPOAdmin/Admin/base.html.twig" %}

{% block page_content %}
    {{ include('@CPOAdmin/Admin/include/header.html.twig') }}
    {{ include('@CPOAdmin/Admin/include/sidebar.html.twig') }}
    <!-- PAGE CONTAINER-->
    <div class="page-container">

        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="header-wrap">
                        <div class="header-button">
                            <div class="account-wrap">
                                <div class="clearfix js-item-menu">
                                    <div class="content">
                                        <h4>O BeeSmart-u</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container container-fluid">
                    <div class="row m-t-30 p-b-30">
                        <div class="col-md-12">
                            <div class="row text">
                                <p>BeeSmart tim čine dva člana, predstavnik Matija Hržić i Denis Martinić.<br>
                                    Tim je prijavljen na Elektroboj 2018 s projektom GSM pčelarske vage.<br><br>
                                    Denis Martinić je student na specijalističkom diplomskom studiju.
                                    <br>
                                    Uz to, proučava audio i energetsku elektroniku, a hobiji su mu biciklizam i društvene znanosti.<br><br>
                                    Matija Hržić je student druge godine na Tehničkom veleučilištu u Zagrebu, smjera Automatizacija i procesno računarstvo. <br>U slobodno vrijeme se bavi elektronikom i tu i tamo pokušava nešto isprogramirati kopiranjem kodova sa stackoverflowa.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/CPO/AdminBundle/Resources/views/Admin/base.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Title Page-->
    <title>BeeSmart CMS</title>

    <!-- Fontfaces CSS-->
    <link href="{{ asset('assets/admin/css/font-face.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/font-awesome-4.7/css/font-awesome.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/font-awesome-5/css/fontawesome-all.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/mdi-font/css/material-design-iconic-font.min.css') }}" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="{{ asset('assets/admin/vendor/bootstrap-4.1/bootstrap.min.css') }}" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="{{ asset('assets/admin/vendor/animsition/animsition.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/wow/animate.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/css-hamburgers/hamburgers.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/slick/slick.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/select2/select2.min.css') }}" rel="stylesheet" media="all">
    <link href="{{ asset('assets/admin/vendor/perfect-scrollbar/perfect-scrollbar.css') }}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{{ asset('assets/admin/css/theme.css') }}?ver={{ now|date("dmYhis") }}" rel="stylesheet" media="all">

</head>

<body>
<div class="page-wrapper">
    {% block page_content %}{% endblock %}
</div>

<!-- Jquery JS-->
<script src="{{ asset('assets/admin/vendor/jquery-3.2.1.min.js') }}"></script>
<!-- Bootstrap JS-->
<script src="{{ asset('assets/admin/vendor/bootstrap-4.1/popper.min.js') }}"></script>
<script src="{{ asset('assets/admin/vendor/bootstrap-4.1/bootstrap.min.js') }}"></script>
<!-- Vendor JS       -->
<script src="{{ asset('assets/admin/vendor/slick/slick.js') }}">
</script>
<script src="{{ asset('assets/admin/vendor/wow/wow.min.js') }}"></script>
<script src="{{ asset('assets/admin/vendor/animsition/animsition.min.js') }}"></script>
<script src="{{ asset('assets/admin/vendor/progressbar/progressbar.js') }}">
</script>
<script src="{{ asset('assets/admin/vendor/counter-up/jquery.waypoints.min.js') }}"></script>
<script src="{{ asset('assets/admin/vendor/counter-up/jquery.counterup.min.js') }}">
</script>
<script src="{{ asset('assets/admin/vendor/circle-progress/circle-progress.min.js') }}"></script>
<script src="{{ asset('assets/admin/vendor/perfect-scrollbar/perfect-scrollbar.js') }}"></script>
<script src="{{ asset('assets/admin/vendor/chartjs/Chart.bundle.min.js') }}"></script>
<script src="{{ asset('assets/admin/vendor/select2/select2.min.js') }}">
</script>

<!-- Main JS-->
<script src="{{ asset('assets/admin/js/main.js') }}"></script>
<script src="{{ asset('assets/admin/js/custom.js') }}"></script>

</body>

</html>
<!-- end document-->

src/CPO/AdminBundle/Resources/views/Admin/kosnica.html.twig
{% extends '@CPOAdmin/Admin/base.html.twig' %}

{% block page_content %}
    {{ include('@CPOAdmin/Admin/include/header.html.twig') }}
    {{ include('@CPOAdmin/Admin/include/sidebar.html.twig') }}
    <!-- PAGE CONTAINER-->
    <div class="page-container">

        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="header-wrap">
                        <div class="header-button">
                            <div class="account-wrap">
                                <div class="clearfix js-item-menu">
                                    <div class="content">
                                        <h4>{{ kosnica.naslov }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container container-fluid">
                    <div class="row m-t-30 p-b-30">
                        <div class="col-md-12">
                            <div class="row">
                                    <div class="col-md-12">
                                        <div class="well">
                                            <div style="float: left" class="col-md-6 col-sm-6 col-xs-12">
                                                <b>Baterija:</b>  {{ kosnica.baterija }} %<br>
                                                <b>Vrijeme:</b> {{ kosnica.vrijeme }}<br>
                                                <b>Temperatura:</b> {{ kosnica.temperatura }}°C<br>
                                                <b>Vlaga:</b> {{ kosnica.vlaga }}kg/m3<br>
                                                <br>
                                                <b>Lokacija:</b> {{ kosnica.lokacija }}<br>
                                                <br>
                                                <b>Težina:</b>  {{ kosnica.tezina }} kg<br>
                                                <b>Promjena težine :</b> {{ kosnica.promjena }}<br>
                                                <b>Temperatura u košnici:</b> {{ kosnica.temperaturaUnutra }}°C<br>
                                                <b>Vlaga u košnici:</b> {{ kosnica.vlagaUnutra }}kg/m3<br>
                                                <b>Broj pčela u košnici:</b> {{ kosnica.brojPcela }}<br>
                                            </div>
                                            <div style="float: left" class="col-md-6 col-sm-6 col-xs-12">
                                                <a href="{{ path('admin_history', {'id': kosnica.id}) }}" class="btn btn-primary">Povijest mjerenja</a><br><br>
                                                <a href="#" class="btn btn-primary">Dohvati lokaciju</a><br><br>
                                                <a href="#" class="btn btn-primary">Dohvati podatke</a><br><br>
                                            </div>
                                            <div style="float: left" class="m-t-30 col-md-12 col-sm-6 col-xs-12">
                                                <label>Izdvoji na dashobard</label>
                                                    <input id="izdvoji" {% if izdvoji == 1 %}checked{% endif %} type="checkbox"><br>
                                                <label>Sleep mode</label>
                                                    <input id="sleep" {% if sleep_mode == 1 %}checked{% endif %} type="checkbox"><br>
                                                <label>Sustav zaštite od životinja</label>
                                                    <input id="animal" {% if animal_mode == 1 %}checked{% endif %} type="checkbox"><br>
                                                <input id="kosnicaId" hidden value="{{ kosnica.identifikacijskiBroj }}">
                                                <small style="float: right"><b>Datum zadnjeg mjerenja:</b> {{ kosnica.datum|date("d.m.Y h:i:s") }}<br></small>
                                            </div>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div style="height: 200px" class="copyright">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/CPO/AdminBundle/Resources/views/Admin/kosnice.html.twig
{% extends '@CPOAdmin/Admin/base.html.twig' %}

{% block page_content %}
    {{ include('@CPOAdmin/Admin/include/header.html.twig') }}
    {{ include('@CPOAdmin/Admin/include/sidebar.html.twig') }}
    <!-- PAGE CONTAINER-->
    <div class="page-container">

        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="header-wrap">
                        <div class="header-button">
                            <div class="account-wrap">
                                <div class="clearfix js-item-menu">
                                    <div class="content">
                                        <h4>Košnice</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>

        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container container-fluid">
                    <div class="row m-t-30 p-b-30">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <table style="width:100%">
                                        <tr>
                                            <th>Naziv košnice</th>
                                            <th>Datum zadnje izmjene</th>
                                            <th>Identifikacijski broj</th>
                                            <th>Pregled</th>
                                        </tr>
                                        {% for item in kosnice %}
                                        <tr>
                                            <td>{{ item.naslov }}</td>
                                            <td>{{ item.datum|date("d.m.Y h:i:s") }}</td>
                                            <td>{{ item.identifikacijskiBroj }}</td>
                                            <td><a href="{{ path('admin_kosnica', {'kosnica': item.id}) }}">Otvori</a> </td>
                                        </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div style="height: 200px" class="copyright">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/CPO/AdminBundle/Resources/views/Admin/povijest.html.twig
{% extends '@CPOAdmin/Admin/base.html.twig' %}

{% block page_content %}
    {{ include('@CPOAdmin/Admin/include/header.html.twig') }}
    {{ include('@CPOAdmin/Admin/include/sidebar.html.twig') }}
    <!-- PAGE CONTAINER-->
    <div class="page-container">

        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="header-wrap">
                        <div class="header-button">
                            <div class="account-wrap">
                                <div class="clearfix js-item-menu">
                                    <div class="content">
                                        <h4>Povijest mjerenja: {{ kosnica.naslov }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a style="float: right;color: #ffffff" href="{{ path('admin_history', {'id': old_kosnica.id }) }}">Povratak na povijest mjerenja</a>
                    </div>
                </div>
            </div>
        </header>

        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container container-fluid">
                    <div class="row m-t-30 p-b-30">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-12">
                                    <div class="well">
                                        <div style="float: left" class="col-md-6 col-sm-6 col-xs-12">
                                            <b>Baterija:</b>  {{ kosnica.baterija }} %<br>
                                            <b>Vrijeme:</b> {{ kosnica.vrijeme }}<br>
                                            <b>Temperatura:</b> {{ kosnica.temperatura }}°C<br>
                                            <b>Vlaga:</b> {{ kosnica.vlaga }}kg/m3<br>
                                            <br>
                                            <b>Lokacija:</b> {{ kosnica.lokacija }}<br>
                                            <br>
                                            <b>Težina:</b>  {{ kosnica.tezina }} kg<br>
                                            <b>Promjena težine :</b> {{ kosnica.promjena }}<br>
                                            <b>Temperatura u košnici:</b> {{ kosnica.temperaturaUnutra }}°C<br>
                                            <b>Vlaga u košnici:</b> {{ kosnica.vlagaUnutra }}kg/m3<br>
                                            <b>Broj pčela u košnici:</b> {{ kosnica.brojPcela }}<br>
                                        </div>
                                        <div style="float: left" class="m-t-30 col-md-12 col-sm-6 col-xs-12">
                                            <label>Izdvoji na dashobard</label>
                                            <input id="izdvoji" {% if izdvoji == 1 %}checked{% endif %} type="checkbox"><br>
                                            <label>Sleep mode</label>
                                            <input id="sleep" {% if sleep_mode == 1 %}checked{% endif %} type="checkbox"><br>
                                            <label>Sustav zaštite od životinja</label>
                                            <input id="animal" {% if animal_mode == 1 %}checked{% endif %} type="checkbox"><br>
                                            <input id="kosnicaId" hidden value="{{ kosnica.identifikacijskiBroj }}">
                                            <small style="float: right"><b>Datum zadnjeg mjerenja:</b> {{ kosnica.datum|date("d.m.Y h:i:s") }}<br></small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div style="height: 200px" class="copyright">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

src/CPO/AdminBundle/Resources/views/Admin/povijest_mjerenja.html.twig
{% extends '@CPOAdmin/Admin/base.html.twig' %}

{% block page_content %}
    {{ include('@CPOAdmin/Admin/include/header.html.twig') }}
    {{ include('@CPOAdmin/Admin/include/sidebar.html.twig') }}
    <!-- PAGE CONTAINER-->
    <div class="page-container">

        <header class="header-desktop">
            <div class="section__content section__content--p30">
                <div class="container-fluid">
                    <div class="header-wrap">
                        <div class="header-button">
                            <div class="account-wrap">
                                <div class="clearfix js-item-menu">
                                    <div class="content">
                                        <h4>Povijest mjerenja: {{ kosnica.naslov }}</h4>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a style="float: right;color: #ffffff" href="{{ path('admin_kosnica', {'kosnica': kosnica.id}) }}">Povratak na košnicu</a>
                    </div>
                </div>
            </div>
        </header>

        <!-- MAIN CONTENT-->
        <div class="main-content">
            <div class="section__content section__content--p30">
                <div class="container container-fluid">
                    <div class="row m-t-30 p-b-30">
                        <div class="col-md-12">
                            <div class="row">
                                <div style="display: none" class="col-md-12">
                                    <div class="row text">
                                        <div class="au-card m-b-30">
                                            <div class="au-card-inner"><div class="chartjs-size-monitor" style="position: absolute; left: 0px; top: 0px; right: 0px; bottom: 0px; overflow: hidden; pointer-events: none; visibility: hidden; z-index: -1;"><div class="chartjs-size-monitor-expand" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:1000000px;height:1000000px;left:0;top:0"></div></div><div class="chartjs-size-monitor-shrink" style="position:absolute;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1;"><div style="position:absolute;width:200%;height:200%;left:0; top:0"></div></div></div>
                                                <canvas id="team-chart" height="354" class="chartjs-render-monitor" style="width:100%;display: block; height: 177px; width: 355px;"></canvas>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="m-b-30"></div>
                                </div>
                                <div class="col-md-12">
                                    <table style="width:100%">
                                        <tr>
                                            <th>Naziv košnice</th>
                                            <th>Datum ažuriranja košnice</th>
                                            <th>Identifikacijski broj</th>
                                            <th>Pregled</th>
                                        </tr>
                                        {% for item in kosnice %}
                                            <tr>
                                                <td>{{ item.naslov }}</td>
                                                <td>{{ item.datum|date("d.m.Y h:i:s") }}</td>
                                                <td>{{ item.identifikacijskiBroj }}</td>
                                                <td><a href="{{ path('admin_povijest_mjerenja', {'id': item.id, 'kosnica': kosnica.id}) }}">Pregledaj podatke</a> </td>
                                            </tr>
                                        {% endfor %}
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <div style="height: 200px" class="copyright">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}